# Generated by Django 5.2.5 on 2025-08-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('security_admin', 'Security Admin'), ('super_admin', 'Super Admin')], default='user', max_length=20),
        ),
    ]
