# Generated by Django 5.2.5 on 2025-08-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_admin_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='access_card_expiry',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='access_card_issue_date',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='access_card_status',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='background_check_date',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='background_check_status',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='drug_test_date',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='drug_test_status',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='fingerprint_date',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='fingerprint_status',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='security_clearance_date',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='security_clearance_expiry',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='security_clearance_level',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='agency_project_cluster_office',
            field=models.CharField(choices=[('undp', 'UNDP - United Nations Development Programme'), ('unicef', "UNICEF - United Nations Children's Fund"), ('who', 'WHO - World Health Organization'), ('unhcr', 'UNHCR - UN Refugee Agency'), ('sdg', 'SDG Integration'), ('climate', 'Climate Change Adaptation'), ('governance', 'Democratic Governance'), ('crisis', 'Crisis Prevention & Recovery'), ('health', 'Health Cluster'), ('education', 'Education Cluster'), ('protection', 'Protection Cluster'), ('shelter', 'Shelter Cluster'), ('co', 'Country Office'), ('ro', 'Regional Office'), ('hq', 'Headquarters'), ('liaison', 'Liaison Office')], default='undp', max_length=200, verbose_name='Name of Agency/Project/Cluster/Office'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='appointment_unit_based_warden',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Appointment- Unit Based Warden'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bsafe',
            field=models.DateField(blank=True, null=True, verbose_name='BSAFE'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='cell_phone_whatsapp',
            field=models.CharField(default='', max_length=20, verbose_name='Cell Phone and WhatsApp Number'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='contact_type',
            field=models.CharField(choices=[('PA', 'PA'), ('CA', 'CA'), ('FTA', 'FTA'), ('TA', 'TA'), ('SC', 'SC'), ('IC', 'IC'), ('UNV', 'UNV')], default='PA', max_length=10, verbose_name='Contact Type'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='duty_station',
            field=models.CharField(choices=[('dhaka', 'Dhaka'), ('chittagong', 'Chittagong'), ('sylhet', 'Sylhet'), ('rajshahi', 'Rajshahi'), ('khulna', 'Khulna'), ('barisal', 'Barisal'), ('rangpur', 'Rangpur'), ('mymensingh', 'Mymensingh'), ('other', 'Other')], default='dhaka', max_length=200, verbose_name='Duty Station'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='email_official',
            field=models.EmailField(default='', max_length=254, verbose_name='Email (Official)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='email_personal',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email (Personal)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='emergency_contact_number',
            field=models.CharField(default='', max_length=20, verbose_name='Emergency Contact Number'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='emergency_contact_relation',
            field=models.CharField(default='', max_length=100, verbose_name='Emergency Contact (Relation)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='id_contact_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='ID/Contact Expiry'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='id_deposit_date',
            field=models.DateField(blank=True, null=True, verbose_name='ID Deposit Date'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='office_location_address',
            field=models.TextField(blank=True, default='', verbose_name='Office Location Address'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='passport_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Passport Number'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='police_station_thana',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Police Station/Thana (Sub Zone)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='post_title_designation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Post Title/Designation'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='r_ser',
            field=models.PositiveIntegerField(default=0, verbose_name='R/Ser'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='radio_call_sign',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Radio Call Sign'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='radio_serial_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Radio Serial ID'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='residential_address',
            field=models.TextField(default='', verbose_name='Residential Address (at Duty Station)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='rfid_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='RFID Number'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='sat',
            field=models.DateField(blank=True, null=True, verbose_name='SAT'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='sbfat',
            field=models.DateField(blank=True, null=True, verbose_name='SBFAT'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='sl',
            field=models.PositiveIntegerField(default=0, verbose_name='SL'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='unid_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='UNID Issue Date'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='unid_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='UNID #'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='unlp_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='UNLP Number'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='zone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Zone'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='zone_name_with_appointment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Zone Name with Appointment'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='relationship',
            field=models.CharField(choices=[('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter')], max_length=20, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=5, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='nationality',
            field=models.CharField(choices=[('afghanistan', 'Afghanistan'), ('albania', 'Albania'), ('algeria', 'Algeria'), ('andorra', 'Andorra'), ('angola', 'Angola'), ('antigua_and_barbuda', 'Antigua and Barbuda'), ('argentina', 'Argentina'), ('armenia', 'Armenia'), ('australia', 'Australia'), ('austria', 'Austria'), ('azerbaijan', 'Azerbaijan'), ('bahamas', 'Bahamas'), ('bahrain', 'Bahrain'), ('bangladesh', 'Bangladesh'), ('barbados', 'Barbados'), ('belarus', 'Belarus'), ('belgium', 'Belgium'), ('belize', 'Belize'), ('benin', 'Benin'), ('bhutan', 'Bhutan'), ('bolivia', 'Bolivia'), ('bosnia_and_herzegovina', 'Bosnia and Herzegovina'), ('botswana', 'Botswana'), ('brazil', 'Brazil'), ('brunei', 'Brunei'), ('bulgaria', 'Bulgaria'), ('burkina_faso', 'Burkina Faso'), ('burundi', 'Burundi'), ('cambodia', 'Cambodia'), ('cameroon', 'Cameroon'), ('canada', 'Canada'), ('cape_verde', 'Cape Verde'), ('central_african_republic', 'Central African Republic'), ('chad', 'Chad'), ('chile', 'Chile'), ('china', 'China'), ('colombia', 'Colombia'), ('comoros', 'Comoros'), ('congo', 'Congo'), ('costa_rica', 'Costa Rica'), ('croatia', 'Croatia'), ('cuba', 'Cuba'), ('cyprus', 'Cyprus'), ('czech_republic', 'Czech Republic'), ('denmark', 'Denmark'), ('djibouti', 'Djibouti'), ('dominica', 'Dominica'), ('dominican_republic', 'Dominican Republic'), ('east_timor', 'East Timor'), ('ecuador', 'Ecuador'), ('egypt', 'Egypt'), ('el_salvador', 'El Salvador'), ('equatorial_guinea', 'Equatorial Guinea'), ('eritrea', 'Eritrea'), ('estonia', 'Estonia'), ('eswatini', 'Eswatini'), ('ethiopia', 'Ethiopia'), ('fiji', 'Fiji'), ('finland', 'Finland'), ('france', 'France'), ('gabon', 'Gabon'), ('gambia', 'Gambia'), ('georgia', 'Georgia'), ('germany', 'Germany'), ('ghana', 'Ghana'), ('greece', 'Greece'), ('grenada', 'Grenada'), ('guatemala', 'Guatemala'), ('guinea', 'Guinea'), ('guinea_bissau', 'Guinea-Bissau'), ('guyana', 'Guyana'), ('haiti', 'Haiti'), ('honduras', 'Honduras'), ('hungary', 'Hungary'), ('iceland', 'Iceland'), ('india', 'India'), ('indonesia', 'Indonesia'), ('iran', 'Iran'), ('iraq', 'Iraq'), ('ireland', 'Ireland'), ('israel', 'Israel'), ('italy', 'Italy'), ('ivory_coast', 'Ivory Coast'), ('jamaica', 'Jamaica'), ('japan', 'Japan'), ('jordan', 'Jordan'), ('kazakhstan', 'Kazakhstan'), ('kenya', 'Kenya'), ('kiribati', 'Kiribati'), ('kuwait', 'Kuwait'), ('kyrgyzstan', 'Kyrgyzstan'), ('laos', 'Laos'), ('latvia', 'Latvia'), ('lebanon', 'Lebanon'), ('lesotho', 'Lesotho'), ('liberia', 'Liberia'), ('libya', 'Libya'), ('liechtenstein', 'Liechtenstein'), ('lithuania', 'Lithuania'), ('luxembourg', 'Luxembourg'), ('madagascar', 'Madagascar'), ('malawi', 'Malawi'), ('malaysia', 'Malaysia'), ('maldives', 'Maldives'), ('mali', 'Mali'), ('malta', 'Malta'), ('marshall_islands', 'Marshall Islands'), ('mauritania', 'Mauritania'), ('mauritius', 'Mauritius'), ('mexico', 'Mexico'), ('micronesia', 'Micronesia'), ('moldova', 'Moldova'), ('monaco', 'Monaco'), ('mongolia', 'Mongolia'), ('montenegro', 'Montenegro'), ('morocco', 'Morocco'), ('mozambique', 'Mozambique'), ('myanmar', 'Myanmar'), ('namibia', 'Namibia'), ('nauru', 'Nauru'), ('nepal', 'Nepal'), ('netherlands', 'Netherlands'), ('new_zealand', 'New Zealand'), ('nicaragua', 'Nicaragua'), ('niger', 'Niger'), ('nigeria', 'Nigeria'), ('north_korea', 'North Korea'), ('north_macedonia', 'North Macedonia'), ('norway', 'Norway'), ('oman', 'Oman'), ('pakistan', 'Pakistan'), ('palau', 'Palau'), ('panama', 'Panama'), ('papua_new_guinea', 'Papua New Guinea'), ('paraguay', 'Paraguay'), ('peru', 'Peru'), ('philippines', 'Philippines'), ('poland', 'Poland'), ('portugal', 'Portugal'), ('qatar', 'Qatar'), ('romania', 'Romania'), ('russia', 'Russia'), ('rwanda', 'Rwanda'), ('saint_kitts_and_nevis', 'Saint Kitts and Nevis'), ('saint_lucia', 'Saint Lucia'), ('saint_vincent_and_the_grenadines', 'Saint Vincent and the Grenadines'), ('samoa', 'Samoa'), ('san_marino', 'San Marino'), ('sao_tome_and_principe', 'Sao Tome and Principe'), ('saudi_arabia', 'Saudi Arabia'), ('senegal', 'Senegal'), ('serbia', 'Serbia'), ('seychelles', 'Seychelles'), ('sierra_leone', 'Sierra Leone'), ('singapore', 'Singapore'), ('slovakia', 'Slovakia'), ('slovenia', 'Slovenia'), ('solomon_islands', 'Solomon Islands'), ('somalia', 'Somalia'), ('south_africa', 'South Africa'), ('south_korea', 'South Korea'), ('south_sudan', 'South Sudan'), ('spain', 'Spain'), ('sri_lanka', 'Sri Lanka'), ('sudan', 'Sudan'), ('suriname', 'Suriname'), ('sweden', 'Sweden'), ('switzerland', 'Switzerland'), ('syria', 'Syria'), ('taiwan', 'Taiwan'), ('tajikistan', 'Tajikistan'), ('tanzania', 'Tanzania'), ('thailand', 'Thailand'), ('togo', 'Togo'), ('tonga', 'Tonga'), ('trinidad_and_tobago', 'Trinidad and Tobago'), ('tunisia', 'Tunisia'), ('turkey', 'Turkey'), ('turkmenistan', 'Turkmenistan'), ('tuvalu', 'Tuvalu'), ('uganda', 'Uganda'), ('ukraine', 'Ukraine'), ('united_arab_emirates', 'United Arab Emirates'), ('united_kingdom', 'United Kingdom'), ('united_states', 'United States'), ('uruguay', 'Uruguay'), ('uzbekistan', 'Uzbekistan'), ('vanuatu', 'Vanuatu'), ('vatican_city', 'Vatican City'), ('venezuela', 'Venezuela'), ('vietnam', 'Vietnam'), ('yemen', 'Yemen'), ('zambia', 'Zambia'), ('zimbabwe', 'Zimbabwe')], default='bangladesh', max_length=100, verbose_name='Nationality'),
        ),
    ]
