# Generated by Django 5.2.5 on 2025-08-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_all_38_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependent',
            name='residential_address',
            field=models.TextField(blank=True, default='', verbose_name='Residential Address (Dependent)'),
        ),
    ]
